'use server';
/**
 * @fileOverview An AI reasoning tool for injecting supporting facts and information into chatbot responses.
 *
 * - reasoningToolForSupportingFacts - A function that enhances chatbot responses with relevant facts.
 * - ReasoningToolForSupportingFactsInput - The input type for the reasoningToolForSupportingFacts function.
 * - ReasoningToolForSupportingFactsOutput - The return type for the reasoningToolForSupportingFacts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReasoningToolForSupportingFactsInputSchema = z.object({
  query: z.string().describe('The user query or question.'),
  chatbotResponse: z.string().describe('The initial response generated by the chatbot.'),
});
export type ReasoningToolForSupportingFactsInput = z.infer<typeof ReasoningToolForSupportingFactsInputSchema>;

const ReasoningToolForSupportingFactsOutputSchema = z.object({
  enhancedResponse: z.string().describe('The chatbot response enhanced with supporting facts and information.'),
});
export type ReasoningToolForSupportingFactsOutput = z.infer<typeof ReasoningToolForSupportingFactsOutputSchema>;

export async function reasoningToolForSupportingFacts(input: ReasoningToolForSupportingFactsInput): Promise<ReasoningToolForSupportingFactsOutput> {
  return reasoningToolForSupportingFactsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'reasoningToolForSupportingFactsPrompt',
  input: {schema: ReasoningToolForSupportingFactsInputSchema},
  output: {schema: ReasoningToolForSupportingFactsOutputSchema},
  prompt: `You are an AI assistant that enhances chatbot responses with supporting facts and information.

  Given the user's query and the chatbot's initial response, identify relevant facts and information that can enhance the response and provide a more comprehensive learning experience for the student.

  User Query: {{{query}}}
  Chatbot Response: {{{chatbotResponse}}}

  Enhanced Response:`, // Provide instructions here to inject supporting facts into the chatbot response.
});

const reasoningToolForSupportingFactsFlow = ai.defineFlow(
  {
    name: 'reasoningToolForSupportingFactsFlow',
    inputSchema: ReasoningToolForSupportingFactsInputSchema,
    outputSchema: ReasoningToolForSupportingFactsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
